"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.generic_error import GenericError
globals()['GenericError'] = GenericError
from openapi_client.model.bad_request import BadRequest


class TestBadRequest(unittest.TestCase):
    """BadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequest(self):
        """Test BadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
