"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.instance_controller_api import InstanceControllerApi  # noqa: E501


class TestInstanceControllerApi(unittest.TestCase):
    """InstanceControllerApi unit test stubs"""

    def setUp(self):
        self.api = InstanceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instance_controller_create_new_whats_app_instance(self):
        """Test case for instance_controller_create_new_whats_app_instance

        Initialize a new WhatsApp instance  # noqa: E501
        """
        pass

    def test_instance_controller_delete_instance(self):
        """Test case for instance_controller_delete_instance

        Delete an instance  # noqa: E501
        """
        pass

    def test_instance_controller_download_media_message(self):
        """Test case for instance_controller_download_media_message

        """
        pass

    def test_instance_controller_get_all_chats(self):
        """Test case for instance_controller_get_all_chats

        Get all your chats  # noqa: E501
        """
        pass

    def test_instance_controller_get_all_contacts(self):
        """Test case for instance_controller_get_all_contacts

        Get all your contacts  # noqa: E501
        """
        pass

    def test_instance_controller_get_instance_data(self):
        """Test case for instance_controller_get_instance_data

        Get an instance  # noqa: E501
        """
        pass

    def test_instance_controller_get_messages_from_chat(self):
        """Test case for instance_controller_get_messages_from_chat

        Get messages from a specific chat  # noqa: E501
        """
        pass

    def test_instance_controller_get_qrcode(self):
        """Test case for instance_controller_get_qrcode

        Get an instance  # noqa: E501
        """
        pass

    def test_instance_controller_get_qrcode_base64(self):
        """Test case for instance_controller_get_qrcode_base64

        Get the qrcode in base64 format  # noqa: E501
        """
        pass

    def test_instance_controller_is_on_whats_app(self):
        """Test case for instance_controller_is_on_whats_app

        Check if number is registerd on WhatsApp  # noqa: E501
        """
        pass

    def test_instance_controller_list_instances(self):
        """Test case for instance_controller_list_instances

        List all instances  # noqa: E501
        """
        pass

    def test_instance_controller_logout_instance(self):
        """Test case for instance_controller_logout_instance

        Logout from an instance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
