"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_webhook_status_schema import UpdateWebhookStatusSchema
globals()['UpdateWebhookStatusSchema'] = UpdateWebhookStatusSchema
from openapi_client.model.webhook_controller_enable_message_webhook_request import WebhookControllerEnableMessageWebhookRequest


class TestWebhookControllerEnableMessageWebhookRequest(unittest.TestCase):
    """WebhookControllerEnableMessageWebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookControllerEnableMessageWebhookRequest(self):
        """Test WebhookControllerEnableMessageWebhookRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebhookControllerEnableMessageWebhookRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
