"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.webhook_controller_api import WebhookControllerApi  # noqa: E501


class TestWebhookControllerApi(unittest.TestCase):
    """WebhookControllerApi unit test stubs"""

    def setUp(self):
        self.api = WebhookControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhook_controller_enable_message_webhook(self):
        """Test case for webhook_controller_enable_message_webhook

        """
        pass

    def test_webhook_controller_get_webhook_stauts(self):
        """Test case for webhook_controller_get_webhook_stauts

        Get an instance webhook data  # noqa: E501
        """
        pass

    def test_webhook_controller_update_webhook_url(self):
        """Test case for webhook_controller_update_webhook_url

        """
        pass


if __name__ == '__main__':
    unittest.main()
