"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.text_messge_single import TextMessgeSingle
globals()['TextMessgeSingle'] = TextMessgeSingle
from openapi_client.model.send_message_controller_send_text_message_to_single_user_request import SendMessageControllerSendTextMessageToSingleUserRequest


class TestSendMessageControllerSendTextMessageToSingleUserRequest(unittest.TestCase):
    """SendMessageControllerSendTextMessageToSingleUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendTextMessageToSingleUserRequest(self):
        """Test SendMessageControllerSendTextMessageToSingleUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendTextMessageToSingleUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
