"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.group_controller_api import GroupControllerApi  # noqa: E501


class TestGroupControllerApi(unittest.TestCase):
    """GroupControllerApi unit test stubs"""

    def setUp(self):
        self.api = GroupControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_controller_add_to_group(self):
        """Test case for group_controller_add_to_group

        Add participants to a group  # noqa: E501
        """
        pass

    def test_group_controller_create_group(self):
        """Test case for group_controller_create_group

        Create a group  # noqa: E501
        """
        pass

    def test_group_controller_demote_participants(self):
        """Test case for group_controller_demote_participants

        Demote certain participants in group  # noqa: E501
        """
        pass

    def test_group_controller_get_admin_groups(self):
        """Test case for group_controller_get_admin_groups

        List all groups in which you are and admin  # noqa: E501
        """
        pass

    def test_group_controller_get_admin_groups_with_participants(self):
        """Test case for group_controller_get_admin_groups_with_participants

        List all groups in which you are and admin along with the participants array  # noqa: E501
        """
        pass

    def test_group_controller_get_group(self):
        """Test case for group_controller_get_group

        Get a group  # noqa: E501
        """
        pass

    def test_group_controller_get_group_invite_code(self):
        """Test case for group_controller_get_group_invite_code

        Get group invite code  # noqa: E501
        """
        pass

    def test_group_controller_leave_group(self):
        """Test case for group_controller_leave_group

        Leave group  # noqa: E501
        """
        pass

    def test_group_controller_list_groups(self):
        """Test case for group_controller_list_groups

        List all groups  # noqa: E501
        """
        pass

    def test_group_controller_promote_participants(self):
        """Test case for group_controller_promote_participants

        Promote certain participants in group  # noqa: E501
        """
        pass

    def test_group_controller_remove_from_group(self):
        """Test case for group_controller_remove_from_group

        Remove participants from group  # noqa: E501
        """
        pass

    def test_group_controller_set_who_can_change_settings(self):
        """Test case for group_controller_set_who_can_change_settings

        Set who can change settings of group  # noqa: E501
        """
        pass

    def test_group_controller_set_who_can_send_message(self):
        """Test case for group_controller_set_who_can_send_message

        Set who can send message in group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
