"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.button import Button
globals()['Button'] = Button
from openapi_client.model.button_message import ButtonMessage


class TestButtonMessage(unittest.TestCase):
    """ButtonMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testButtonMessage(self):
        """Test ButtonMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ButtonMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
