"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_group_data import CreateGroupData
globals()['CreateGroupData'] = CreateGroupData
from openapi_client.model.group_controller_create_group_request import GroupControllerCreateGroupRequest


class TestGroupControllerCreateGroupRequest(unittest.TestCase):
    """GroupControllerCreateGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupControllerCreateGroupRequest(self):
        """Test GroupControllerCreateGroupRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupControllerCreateGroupRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
