"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contact_data import ContactData


class TestContactData(unittest.TestCase):
    """ContactData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactData(self):
        """Test ContactData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContactData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
