"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.send_v_card_data import SendVCardData
globals()['SendVCardData'] = SendVCardData
from openapi_client.model.send_message_controller_send_template_messsage_request import SendMessageControllerSendTemplateMesssageRequest


class TestSendMessageControllerSendTemplateMesssageRequest(unittest.TestCase):
    """SendMessageControllerSendTemplateMesssageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendTemplateMesssageRequest(self):
        """Test SendMessageControllerSendTemplateMesssageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendTemplateMesssageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
