"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.media_message_keys import MediaMessageKeys
globals()['MediaMessageKeys'] = MediaMessageKeys
from openapi_client.model.instance_controller_download_media_message_request import InstanceControllerDownloadMediaMessageRequest


class TestInstanceControllerDownloadMediaMessageRequest(unittest.TestCase):
    """InstanceControllerDownloadMediaMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceControllerDownloadMediaMessageRequest(self):
        """Test InstanceControllerDownloadMediaMessageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceControllerDownloadMediaMessageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
