"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_section import ListSection
globals()['ListSection'] = ListSection
from openapi_client.model.send_list_message_data import SendListMessageData


class TestSendListMessageData(unittest.TestCase):
    """SendListMessageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendListMessageData(self):
        """Test SendListMessageData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendListMessageData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
