"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.send_message_controller_api import SendMessageControllerApi  # noqa: E501


class TestSendMessageControllerApi(unittest.TestCase):
    """SendMessageControllerApi unit test stubs"""

    def setUp(self):
        self.api = SendMessageControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send_message_controller_send_audio_message(self):
        """Test case for send_message_controller_send_audio_message

        Send an audio to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_buttons_message(self):
        """Test case for send_message_controller_send_buttons_message

        Send an interactive template message to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_buttons_message_with_media(self):
        """Test case for send_message_controller_send_buttons_message_with_media

        Send an interactive template message with mediaHeader to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_document_message(self):
        """Test case for send_message_controller_send_document_message

        Send an document to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_image_message(self):
        """Test case for send_message_controller_send_image_message

        Send an image message to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_list_message(self):
        """Test case for send_message_controller_send_list_message

        Send an vacard message to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_location_message(self):
        """Test case for send_message_controller_send_location_message

        Send an location to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_media_url(self):
        """Test case for send_message_controller_send_media_url

        Send a media message via a URL  # noqa: E501
        """
        pass

    def test_send_message_controller_send_template_messsage(self):
        """Test case for send_message_controller_send_template_messsage

        Send an vacard message to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_text_message(self):
        """Test case for send_message_controller_send_text_message

        Send a text message to multiple WhatsApp users  # noqa: E501
        """
        pass

    def test_send_message_controller_send_text_message_to_single_user(self):
        """Test case for send_message_controller_send_text_message_to_single_user

        Send a text message to an WhatsApp User  # noqa: E501
        """
        pass

    def test_send_message_controller_send_video_message(self):
        """Test case for send_message_controller_send_video_message

        Send an video to an WhatsApp User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
