"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.location_cordinates import LocationCordinates
globals()['LocationCordinates'] = LocationCordinates
from openapi_client.model.location_message import LocationMessage


class TestLocationMessage(unittest.TestCase):
    """LocationMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationMessage(self):
        """Test LocationMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocationMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
