"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.text_messge_single import TextMessgeSingle


class TestTextMessgeSingle(unittest.TestCase):
    """TextMessgeSingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextMessgeSingle(self):
        """Test TextMessgeSingle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMessgeSingle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
