"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.media_url_message import MediaUrlMessage
globals()['MediaUrlMessage'] = MediaUrlMessage
from openapi_client.model.send_message_controller_send_media_url_request import SendMessageControllerSendMediaUrlRequest


class TestSendMessageControllerSendMediaUrlRequest(unittest.TestCase):
    """SendMessageControllerSendMediaUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendMediaUrlRequest(self):
        """Test SendMessageControllerSendMediaUrlRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendMediaUrlRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
