"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_row import ListRow
globals()['ListRow'] = ListRow
from openapi_client.model.list_section import ListSection


class TestListSection(unittest.TestCase):
    """ListSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSection(self):
        """Test ListSection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
