"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.media_message_keys import MediaMessageKeys


class TestMediaMessageKeys(unittest.TestCase):
    """MediaMessageKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaMessageKeys(self):
        """Test MediaMessageKeys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MediaMessageKeys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
