"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contact_data import ContactData
globals()['ContactData'] = ContactData
from openapi_client.model.send_v_card_data import SendVCardData


class TestSendVCardData(unittest.TestCase):
    """SendVCardData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendVCardData(self):
        """Test SendVCardData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendVCardData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
