"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.button_message import ButtonMessage
globals()['ButtonMessage'] = ButtonMessage
from openapi_client.model.send_message_controller_send_buttons_message_request import SendMessageControllerSendButtonsMessageRequest


class TestSendMessageControllerSendButtonsMessageRequest(unittest.TestCase):
    """SendMessageControllerSendButtonsMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendButtonsMessageRequest(self):
        """Test SendMessageControllerSendButtonsMessageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendButtonsMessageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
