"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.text_messge import TextMessge
globals()['TextMessge'] = TextMessge
from openapi_client.model.send_message_controller_send_text_message_request import SendMessageControllerSendTextMessageRequest


class TestSendMessageControllerSendTextMessageRequest(unittest.TestCase):
    """SendMessageControllerSendTextMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendTextMessageRequest(self):
        """Test SendMessageControllerSendTextMessageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendTextMessageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
