"""
    Api documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.send_list_message_data import SendListMessageData
globals()['SendListMessageData'] = SendListMessageData
from openapi_client.model.send_message_controller_send_list_message_request import SendMessageControllerSendListMessageRequest


class TestSendMessageControllerSendListMessageRequest(unittest.TestCase):
    """SendMessageControllerSendListMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMessageControllerSendListMessageRequest(self):
        """Test SendMessageControllerSendListMessageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMessageControllerSendListMessageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
